version: "3.8"

services:

  backend:
    build: ./backend
    container_name: carepulse-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  ai-service:
    build: ./ai-doctor-service
    container_name: carepulse-ai
    ports:
      - "4500:4500"
    env_file:
      - ./ai-doctor-service/.env

  videocall:
    build: ./videocall
    container_name: carepulse-videocall
    ports:
      - "4000:4000"
    env_file:
      - ./videocall/.env